function featureNames = feature_names()

featureNames = {'mean',...
                'variance',...
                'skewness',...
                'kurtosis',...
                'meanPSD', ...
                'variancePSD',...
                'skewnessPSD',...
                'kurtosisPSD',...
                'peakPSD',...
                'peaklocationPSD',...
                'energyPSD',...
                'centroidlocationPSD'};